# This workspace publishes the ktm go program to GitHub releases

name: Publish ktm

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go 1.17
        uses: actions/setup-go@v4
        with:
          go-version: 1.17
        id: go
      - name: Build
        run: go build -o ktm
      - name: Create Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ github.ref }}
          prerelease: false
          title: "Release ${{ github.ref }}"
          files: |
            ktm